language: objective-c

branches:
 only:
 - master

xcode_project: \#github-ios.xcodeproj
xcode_scheme: \#github-iosTests
osx_image: xcode8.3

script:
- xcodebuild clean build test -workspace \#github-ios.xcworkspace -scheme \#github-iosTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3'