language: objective-c

branches:
 only:
 - master

xcode_project: \#github-ios.xcodeproj
xcode_scheme: \#github-iosTests
osx_image: xcode8.3

before_install:
- cd \#github-ios
- cp ./mock-GoogleService-Info.plist ./GoogleService-Info.plist
- cp ./mock-GithubConfig-Info.plist ./GithubConfig-Info.plist
- cd -

script:
- xcodebuild clean build test -workspace \#github-ios.xcworkspace -scheme \#github-iosTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3'